/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package hexocalc */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */




/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
// typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif


/* Return type for HexowlCalculate */
typedef struct hexowl_calculate_return {
	GoUint8 success; /* success */
	GoString decVal; /* decVal */
	GoString hexVal; /* hexVal */
	GoString binVal; /* binVal */
	GoUint32 calcTime;	/* calcTime */
} hexowl_calculate_return_t;

typedef void (*hexowl_print_func_t)(GoString str);
typedef void (*hexowl_clear_func_t)(void);
typedef int (*hexowl_flist_func_t)(char *str);
typedef int (*hexowl_fopen_func_t)(GoString name, GoString mode);
typedef int (*hexowl_fclose_func_t)(void);
typedef int (*hexowl_fwrite_func_t)(const void *data, size_t size);
typedef int (*hexowl_fread_func_t)(void *data, size_t size);

//go:noinline
extern hexowl_calculate_return_t HexowlCalculate(const char *input);

//go:noinline
extern void HexowlInit(
	hexowl_print_func_t printfunc,
	GoUint32 limit,
	hexowl_clear_func_t clearfunc,
	hexowl_flist_func_t listfunc,
	hexowl_fopen_func_t openfunc,
	hexowl_fclose_func_t closefunc,
	hexowl_fwrite_func_t writefunc,
	hexowl_fread_func_t readfunc);

//go:noinline
extern GoUint64 GetFreeMem();

#ifdef __cplusplus
}
#endif
